#This file contains properties for dev environment

http:
  host: "0.0.0.0"
  port: "8081"
  
uri:
  path: "/validate" 
    
https:
  host: "0.0.0.0"
  port: "8091"
  
oauth:
  token:
    ttl: "3600"
    path: "/access-token"
  supportedgranttypes:
    all: "AUTHORIZATION_CODE,IMPLICIT,RESOURCE_OWNER_PASSWORD_CREDENTIALS,CLIENT_CREDENTIALS"
  scopes: 
    all: "READ, WRITE"
    default: "READ"
    
  
    
    